camera_pub_node:
  ros__parameters:
    camera_source: "2"   # webcam id or video path !absolute path!

gt_test_node:
  ros__parameters:
    max_path: 5000
    is_2d: True
    testing: True
    marker_size_mm: 151.0
    camera_matrix: [426.300, 313.605, 427.782, 237.654] # fx, cx, fy, cy
    distortion_matrix: [-0.09070626,  0.08382796,  0.,          0.,          0.        ]
